### ISSUE TITLE
`Not found pair character for [.` when using new highlight blockquote syntax

### ISSUE THREAD

**Issue by Takashicc** [textlint-rule/textlint-rule-no-unmatched-pair#16]
以下のように[新しくなったハイライトシンタックス](https://github.com/orgs/community/discussions/16925)を利用してtextlintを実行すると、

```md
> [!NOTE]
> some content
```

Not found pair characterが発生しました。

直るとうれしいです 🙏 

```txt
  125:4  error  Not found pair character for [.
                    
You should close this sentence with ].
This pair mark is called angled bracket[]  ja-technical-writing/no-unmatched-pair
```

**Comment by azu** [comment]
https://github.com/textlint-rule/textlint-rule-no-unmatched-pair/releases/tag/v2.0.0
でおそらく修正できたと思います。
以前は `!` でセンテンスが分割されてて、`[` に対するペアが別のセンテンスにあってエラーが出ていたのだと思います。
